### ISSUE TITLE
Filter f1s curves by date when getting a single contract

### ISSUE THREAD

**Issue by juan-pe** [Som-Energia/infoenergia-api#7]
Actually when we ask to `/f1/:contractId:`  the endpoint returns all f1s curves that it has.

In this issue we want that the endpoint filters by date adding the parameters `from_` and `to_` to the query params of the request.

If the param `to_` is not present, the endpoint will return the f1s curves from the specified date in `from_` parameter util now.

**Comment by JoanaFigueira** [comment]
Already implemented: see commit 41a1d773aff19b96736cdf3558116465c9c0ed83
